### ISSUE TITLE
Three updates about System Level Outcomes

### ISSUE THREAD

**Issue by Mttbnchtt** [SDG-InterfaceOntology/sdgio#129]
I have made 3 updates to the branch System Level Outcome. It is a good idea to double check what I did.
1. I derived the definition of "poverty reduction" from its rdfs: comment. Is acceptable? Is it correct? Should or could it be improved?
2. I derived the definition of "improvement of food and nutrition security" from its rdfs: comment. Is the definition acceptable? Is it correct? Should or could it be improved?
3. I added "improvement of natural resources and ecosystem services". Is it all right?

**Comment by pbuttigieg** [comment]
Some comments:

### Definitions
Keep in mind the kind of entity you're defining:

![image](https://user-images.githubusercontent.com/2276146/56578123-1f56e400-65cd-11e9-893b-0c77e65aecff.png)

An SLO is an `objective specification`, which means it can't improve anything by itself - it's just a statement of objective. A more appropriate definition would be:

> A system level outcome which specifies that planned processes undertaken by the CGIAR aim to promote the availability, access, use, and stability of or to a food supply.

Use the same approach for the other SLOs.

### ORCID

Watch out when duplicating a class: the duplication process seems to make the ORCID annotation property (AP) a string rather than an IRI entry.

Keep the ORCID AP that looks like this when double-clicked:
![image](https://user-images.githubusercontent.com/2276146/56578591-4feb4d80-65ce-11e9-9580-5eb0a257d875.png)

Remove the one that looks like this:

![image](https://user-images.githubusercontent.com/2276146/56578804-cd16c280-65ce-11e9-9d52-db25052b3f7d.png)

### Labels

Pending #128, we should improve the labels as they sound quite clunky.

**Comment by pbuttigieg** [comment]
Once we're done here, we'll make these instances of SDGIO_00020232 rather than classes and then create a pull request.

**Comment by Mttbnchtt** [comment]
I modified the three definitions. Let me know if they are ok now or there is more that I should consider. 
I fixed the ORCID issue.

**Comment by pbuttigieg** [comment]
Can this be closed now @Mttbnchtt ?

**Comment by Mttbnchtt** [comment]
Yes, we can close this issue. I have just realized that SDGIO_00020232 is the class system level outocome. So we are done with this.
