### ISSUE TITLE
Addition or import of 'resource'?

### ISSUE THREAD

**Issue by Mttbnchtt** [SDG-InterfaceOntology/sdgio#180]
Some days ago we created a new class called _resource_. However, CCOs has already a class called _Resource_. Should we delete the new SDGIO _resource_ and import the CCOs _Resource_?
@marieALaporte 
@pbuttigieg

**Comment by mark-jensen** [comment]
`resource` was added to the SDGIO quite a while back. See #31. It’s a tricky one to define. The CCO term is aligned with it in spirit, defined somewhat differently, but I believe both terms are grounded in the same corner of reality. The CCO one should be axiomitzed, I'll look into that. At this stage, I wouldn’t import it from CCO since it has been in SDGIO for quite a while, and there is still some vetting on both sides that needs to be done. Perhaps inlcude the CCO IRI as an external refernce for now?

**Comment by Mttbnchtt** [comment]
Thanks @mark-jensen for the explanation. I agree with leaving _resource_ as it is in SDGIO. I will include the CCO IRI as an external reference.
