### ISSUE TITLE
"during which" or "through which"

### ISSUE THREAD

**Issue by Mttbnchtt** [SDG-InterfaceOntology/sdgio#183]
So far, we define processes using the phrase _during which_. However, what is important is not merely the temporal aspect of the process. It is also important that through a certain process a specific result follows. Should we say instead: P is a planned process _through which_ an agent etc.?
@marieALaporte 
@pbuttigieg

**Comment by pbuttigieg** [comment]
> what is important is not merely the temporal aspect of the process. It is also important that through a certain process a specific result follows. 

I don't think there's anything "mere" about it. Many instances of these processes will not have the intended outcome, but they will still be classified under these categories in project management systems. 

> Should we say instead: P is a planned process through which an agent etc.?

Due to the above, we should not say this. "During" correctly indicates that the agent is attempting to fulfill the objective, and may or may not achieve this goal. 

This is a concern I have about the "realizes/concretizes" axiom convention: there is no guarantee that the objective is realised. We can likely solve this by saying that the process realises/concretises a plan that has the objective as a part.

**Comment by Mttbnchtt** [comment]
On a purely theoretical ground, I still see some issue. However, the answer is good enough for our needs concerning SDGIO. Thanks very much.
